import {useMemo,useState} from 'react';
import {Apple,CalendarDays,ChevronRight,CircleUserRound,Droplets,Home,LineChart,Plus,Search,Target,Trash2,Utensils,X} from 'lucide-react';
import {foods,initialMeals} from './data';
import type {Food,Meal,MealType} from './types';
type Tab='Overview'|'Diary'|'Add'|'Progress'|'You';
const goal={calories:2300,protein:180,carbs:250,fat:70,water:2500};
const total=(m:Meal[],k:'calories'|'protein'|'carbs'|'fat')=>m.reduce((s,x)=>s+x[k],0);
const pc=(v:number,max:number)=>`${Math.min(100,Math.round(v/max*100))}%`;

export function App(){
 const[tab,setTab]=useState<Tab>('Overview'),[meals,setMeals]=useState(initialMeals),[water,setWater]=useState(1750),[query,setQuery]=useState(''),[mealType,setMealType]=useState<MealType>('Lunch'),[toast,setToast]=useState('');
 const totals=useMemo(()=>({calories:total(meals,'calories'),protein:total(meals,'protein'),carbs:total(meals,'carbs'),fat:total(meals,'fat')}),[meals]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),1700)};
 const add=(f:Food)=>{setMeals(v=>[...v,{...f,mealId:crypto.randomUUID(),type:mealType,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}]);setTab('Diary');notify(`${f.name} added`)};
 return <div className="shell"><header className="hero"><div className="top"><b>Fitty<span>.</span></b><button onClick={()=>setTab('You')}><CircleUserRound/></button></div><div className="motto"><p>Small choices.</p><h1>Better nutrition.</h1></div><div className="date"><CalendarDays/> Today, 15 Sep <ChevronRight/></div><div className="week">{['M 14','T 15','W 16','T 17','F 18','S 19','S 20'].map((d,i)=><button className={i===1?'active':''} key={d}><span>{d[0]}</span><b>{d.slice(2)}</b></button>)}</div></header>
 <main>{tab==='Overview'&&<Overview t={totals} water={water} add={()=>setTab('Add')} drink={()=>{setWater(v=>Math.min(goal.water,v+250));notify('250 ml water added')}}/>}{tab==='Diary'&&<Diary meals={meals} add={()=>setTab('Add')} remove={id=>{setMeals(v=>v.filter(x=>x.mealId!==id));notify('Meal removed')}}/>}{tab==='Add'&&<AddFood query={query} setQuery={setQuery} mealType={mealType} setMealType={setMealType} add={add} close={()=>setTab('Overview')}/>} {tab==='Progress'&&<Progress t={totals} water={water}/>} {tab==='You'&&<Profile/>}</main>
 {toast&&<div className="toast">{toast}</div>}<nav><Nav label="Overview" icon={<Home/>} active={tab==='Overview'} go={()=>setTab('Overview')}/><Nav label="Diary" icon={<Utensils/>} active={tab==='Diary'} go={()=>setTab('Diary')}/><button className="main-add" onClick={()=>setTab('Add')}><Plus/></button><Nav label="Progress" icon={<LineChart/>} active={tab==='Progress'} go={()=>setTab('Progress')}/><Nav label="You" icon={<CircleUserRound/>} active={tab==='You'} go={()=>setTab('You')}/></nav></div>
}

function Overview({t,water,add,drink}:{t:Record<string,number>,water:number,add:()=>void,drink:()=>void}){return <section className="content"><div className="heading"><div><p className="eyebrow">Daily overview</p><h2>You have <em>{Math.max(0,goal.calories-t.calories).toLocaleString()}</em> kcal left</h2></div><Target/></div><article className="calories card"><div className="ring" style={{'--p':pc(t.calories,goal.calories)} as React.CSSProperties}><div><strong>{t.calories.toLocaleString()}</strong><span>of 2,300 kcal</span></div></div><div><span className="muted">Calories</span><h3>Right on track</h3><p>Your meals are balanced today. Keep dinner rich in protein and vegetables.</p><button className="primary" onClick={add}>Log a meal <Plus/></button></div></article><div className="macros"><Macro l="Protein" v={t.protein} g={180} c="#008f7a"/><Macro l="Carbs" v={t.carbs} g={250} c="#68c9bb"/><Macro l="Fat" v={t.fat} g={70} c="#ae00e8"/></div><article className="water card"><div className="water-icon"><Droplets/></div><div><span className="muted">Hydration</span><h3>{(water/1000).toFixed(2)} L <small>/ 2.5 L</small></h3><div className="bar"><i style={{width:pc(water,2500)}}/></div></div><button onClick={drink}>+ 250 ml</button></article><div className="insight"><Apple/><div><b>Today’s insight</b><p>You’re close to your protein goal. Add yogurt, eggs, chicken or legumes next.</p></div></div></section>}
function Macro({l,v,g,c}:{l:string,v:number,g:number,c:string}){return <div className="macro card"><div><span>{l}</span><b>{v}<small> / {g}g</small></b></div><div className="bar"><i style={{width:pc(v,g),background:c}}/></div><p>{Math.max(0,g-v)}g remaining</p></div>}
function Diary({meals,add,remove}:{meals:Meal[],add:()=>void,remove:(id:string)=>void}){return <section className="content page"><Title small="Food diary" title="Today’s meals" action={<button className="primary" onClick={add}><Plus/> Add food</button>}/>{(['Breakfast','Lunch','Dinner','Snack'] as MealType[]).map(type=><div className="meal" key={type}><div className="meal-head"><h3>{type}</h3><span>{total(meals.filter(m=>m.type===type),'calories')} kcal</span></div>{meals.filter(m=>m.type===type).map(m=><div className="meal-row" key={m.mealId}><i><Utensils/></i><div><b>{m.name}</b><span>{m.serving} · {m.time}</span></div><strong>{m.calories}</strong><button onClick={()=>remove(m.mealId)}><Trash2/></button></div>)}{!meals.some(m=>m.type===type)&&<button className="empty" onClick={add}><Plus/> Add {type.toLowerCase()}</button>}</div>)}</section>}
function AddFood({query,setQuery,mealType,setMealType,add,close}:{query:string,setQuery:(s:string)=>void,mealType:MealType,setMealType:(m:MealType)=>void,add:(f:Food)=>void,close:()=>void}){return <section className="content page"><Title small="Quick log" title="Add food" action={<button className="close" onClick={close}><X/></button>}/><div className="types">{(['Breakfast','Lunch','Dinner','Snack'] as MealType[]).map(x=><button className={mealType===x?'chosen':''} onClick={()=>setMealType(x)}>{x}</button>)}</div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search foods and meals"/></label><p className="list-label">{query?'Search results':'Frequently added'}</p>{foods.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())).map(f=><button className="food" onClick={()=>add(f)} key={f.id}><i><Apple/></i><div><b>{f.name}</b><span>{f.serving}</span><small>P {f.protein}g · C {f.carbs}g · F {f.fat}g</small></div><strong>{f.calories}<small> kcal</small></strong><Plus/></button>)}</section>}
function Progress({t,water}:{t:Record<string,number>,water:number}){return <section className="content page"><Title small="Weekly report" title="Your progress"/><div className="score"><span>Nutrition score</span><strong>82</strong><small>/100</small><p>Great consistency. You logged food on 6 of the last 7 days.</p></div><div className="chart card"><h3>Calories this week</h3><div>{[68,84,72,92,78,86,Math.round(t.calories/23)].map((v,i)=><i key={i} style={{height:`${v}%`}}><span>{['M','T','W','T','F','S','S'][i]}</span></i>)}</div></div><div className="stats"><div><span>Average calories</span><b>2,086</b></div><div><span>Water today</span><b>{(water/1000).toFixed(2)} L</b></div></div></section>}
function Profile(){return <section className="content page"><Title small="Your plan" title="Hi, Alex"/><div className="profile"><i>A</i><div><b>Balanced nutrition</b><span>Maintain weight · Active</span></div></div><div className="settings">{['Daily nutrition goals','Dietary preferences','Reminders & notifications','Connected health data','Account & privacy'].map(x=><button>{x}<ChevronRight/></button>)}</div></section>}
function Title({small,title,action}:{small:string,title:string,action?:React.ReactNode}){return <div className="heading"><div><p className="eyebrow">{small}</p><h2>{title}</h2></div>{action}</div>}
function Nav({label,icon,active,go}:{label:string,icon:React.ReactNode,active:boolean,go:()=>void}){return <button className={active?'selected':''} onClick={go}>{icon}<span>{label}</span></button>}
